src/main/java/org/example/products/controller/ProductController.java
src/main/java/org/example/products/dto/request/ProductCreateRequest.java
src/main/java/org/example/products/dto/response/ProductResponse.java
src/main/java/org/example/products/repository/ProductRepository.java
src/main/java/org/example/products/repository/entity/ProductEntity.java
src/main/java/org/example/products/service/ProductService.java
src/main/java/org/example/security/config/SecurityConfig.java

1. 작업 내용
게시글 생성 기능 구현 (제목, 물품 종류, 설명, 가격 등)
2. 이미지 추가
" width="50%" height="50%">
" width="50%" height="50%")
3. 추가해야 할 기능
이미지 업로드 기능 추가
4. 기타(생략)
5. 이슈 링크
cammoa_backend #8

[feat] 게시글 생성 기능 구현

---

src/main/java/org/example/common/ResponseEnum/SuccessResponseEnum.java
src/main/java/org/example/exception/impl/ResourceException.java
src/main/java/org/example/security/config/SecurityConfig.java
src/main/java/org/example/security/filter/JwtAuthenticationFilter.java
src/main/java/org/example/security/service/UserDetailsServiceImpl.java
src/main/java/org/example/users/controller/UserController.java
src/main/java/org/example/users/dto/request/ChangePasswordRequest.java
src/main/java/org/example/users/repository/entity/UserEntity.java
src/main/java/org/example/users/service/UserService.java
src/main/java/org/example/users/service/UserServiceImpl.java

- 비밀번호 변경 기능 구현
- role 추가로 인해 발생하는 에러 해결
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #29

[feat] 비밀번호 변경 기능 구현

---

src/main/java/org/example/common/ResponseEnum/ErrorResponseEnum.java
src/main/java/org/example/common/ResponseEnum/SuccessResponseEnum.java
src/main/java/org/example/security/config/SecurityConfig.java
src/main/java/org/example/users/controller/UserController.java
src/main/java/org/example/users/dto/request/DeleteUserRequest.java
src/main/java/org/example/users/repository/UserRepository.java
src/main/java/org/example/users/repository/UserRepositoryImpl.java
src/main/java/org/example/users/service/UserService.java
src/main/java/org/example/users/service/UserServiceImpl.java

- 회원 탈퇴 기능 구현
- SecurityConfig build 문제 해결
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #31

[feat] 회원 탈퇴 기능 구현

---

src/main/java/org/example/users/controller/UserController.java
src/main/java/org/example/users/dto/response/ProfileResponse.java
src/main/java/org/example/users/repository/entity/UserEntity.java
src/main/java/org/example/users/service/UserService.java
src/main/java/org/example/users/service/UserServiceImpl.java

- 프로필 정보 조회 api 구현
<br/>
<br/>
- 작성한 공동구매 목록, 참여한 공동구매 목록, 알림 조회 기능
<br/>
- user부분에서 nickname 추가
<br/>
cammoa_backend #35

[feat] 프로필 정보 조회

---

src/main/java/org/example/products/dto/response/ProductSimpleResponse.java
src/main/java/org/example/products/repository/ProductRepository.java
src/main/java/org/example/products/service/ProductService.java
src/main/java/org/example/users/controller/UserController.java
src/main/java/org/example/users/service/UserService.java
src/main/java/org/example/users/service/UserServiceImpl.java

- 프로필 조회 시 작성한 공동구매 목록(myGroupBuyings) 반환 기능 추가
- 예외처리 방식 통일(AuthException, ResourceException)
<br/>
<br/>
<br/>
- 참여한 공동구매 목록, 알림 기능
<br/>
- 
<br/>
cammoa_backend #36

[feat] 작성한 공동구매 목록 조회

---

src/main/java/org/example/common/ResponseEnum/ErrorResponseEnum.java
src/main/java/org/example/users/controller/UserController.java
src/main/java/org/example/users/dto/request/UserCreateRequest.java
src/main/java/org/example/users/dto/response/UserResponse.java
src/main/java/org/example/users/repository/entity/UserEntity.java
src/main/java/org/example/users/service/UserServiceImpl.java

- 회원가입 시 닉네임 입력하도록 UserEntity, UserCreateRequest에 닉네임 추가
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #34

[refactor] 회원가입

---

src/main/java/org/example/chat/controller/ChatController.java
src/main/java/org/example/chat/service/ChatServiceimpl.java
src/main/java/org/example/common/ResponseEnum/SuccessResponseEnum.java
src/main/java/org/example/products/controller/ProductController.java
src/main/java/org/example/products/repository/ProductRepository.java
src/main/java/org/example/products/repository/entity/ProductEntity.java
src/main/java/org/example/products/service/ProductService.java

- 게시글 삭제 API 구현
- 삭제 성공 시 200 OK 및 "Post Deleted Successfully" 응답 반환
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #44

[feat]게시글 삭제 기능 구현

---

.idea/dataSources.xml
src/main/java/org/example/common/ResponseEnum/ErrorResponseEnum.java
src/main/java/org/example/common/ResponseEnum/SuccessResponseEnum.java
src/main/java/org/example/products/controller/ParticipationController.java
src/main/java/org/example/products/dto/request/GroupBuyingJoinRequest.java
src/main/java/org/example/products/repository/ParticipationRepository.java
src/main/java/org/example/products/repository/entity/ParticipationEntity.java
src/main/java/org/example/products/service/ProductService.java

- 공동구매 참여 API 구현 (POST /api/group-buyings/join)
- 참여 시 ProductEntity.currentParticipants 값 증가
- 중복 참여 방지 로직 추가
<br/>
<br/>
-참여 취소 기능
<br/>
- ErrorResponseEnum의 한글 메시지를 영어로 통일
<br/>
cammoa_backend #45

[Feat] 공동구매 참여

---

src/main/java/org/example/common/ResponseEnum/ErrorResponseEnum.java
src/main/java/org/example/common/ResponseEnum/SuccessResponseEnum.java
src/main/java/org/example/products/controller/ParticipationController.java
src/main/java/org/example/products/controller/ProductController.java
src/main/java/org/example/products/repository/ParticipationRepository.java
src/main/java/org/example/products/service/ParticipationService.java

- 공동구매 참여 취소 API 구현
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #56

[feat] 공동구매 참여 취소 기능 구현

---

src/main/java/org/example/products/repository/ParticipationRepository.java
src/main/java/org/example/products/service/ParticipationService.java
src/main/java/org/example/users/controller/UserController.java

- 참여한 공동구매 목록 조회 api 구현
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #57

[feat] 참여한 공동구매 목록 조회

---

src/main/java/org/example/chat/controller/ChatController.java
src/main/java/org/example/chat/dto/response/GetChatRoomsResponse.java
src/main/java/org/example/chat/repository/ChatParticipantJpaRepository.java
src/main/java/org/example/chat/repository/ChatParticipantRepository.java
src/main/java/org/example/chat/repository/ChatParticipantRepositoryImpl.java
src/main/java/org/example/chat/repository/ChatRoomJpaRepository.java
src/main/java/org/example/chat/repository/ChatRoomRepository.java
src/main/java/org/example/chat/repository/ChatRoomRepositoryImpl.java
src/main/java/org/example/chat/repository/ReadStatusJpaRepository.java
src/main/java/org/example/chat/repository/ReadStatusRepository.java
src/main/java/org/example/chat/repository/ReadStatusRepositoryImpl.java
src/main/java/org/example/chat/service/ChatService.java
src/main/java/org/example/chat/service/ChatServiceimpl.java
src/main/java/org/example/common/ResponseEnum/SuccessResponseEnum.java
src/main/java/org/example/users/repository/entity/UserEntity.java
src/main/java/org/example/users/service/UserServiceImpl.java

- roomId로 채팅방 조회
- 채팅방 참여자 여부 확인 후 채팅방 나가기
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #67

[feat] 채팅방 나가기 기능 구현

---

src/main/java/org/example/chat/config/StompWebSocketConfig.java
src/main/java/org/example/chat/controller/StompController.java
src/main/java/org/example/chat/dto/ChatMessageDto.java
src/main/java/org/example/chat/service/RedisPubSubService.java
src/main/java/org/example/products/dto/response/ProductListResponse.java
src/main/java/org/example/redis/RedisConfig.java
src/main/java/org/example/security/config/SecurityConfig.java

- redis PubSub 구조를 추가해 여러 서버에서 채팅 기능 가능하도록 수정
<br/>
-
<br/>
- 현재 정상적으로 동작하지만 메시지 전송 테스트 후 정확히 확인
<br/>
cammoa_backend #69

[refactor] redis PubSub 추가

---

src/main/java/org/example/users/service/UserServiceImpl.java

- 에러 이넘 수정
<br/>
-
<br/>
- 
<br/>
cammoa_backend #78

[refactor] 에러 이넘 수정

---

src/main/resources/application.yml

- application.yml 에서 DATABASE_HOST 변수 추가
<br/>
-
<br/>
- 
<br/>

[refactor] 설정 변경

---

src/main/java/org/example/email/service/EmailServiceImpl.java

- application.yml 수정으로 인해 코드 수정
<br/>
-
<br/>
- 
<br/>

[refactor] 변수명 수정

---

src/main/resources/application.yml

- 파일 업로드 디렉토리 주소 환경변수로 설정 
<br/>
-
<br/>
- 
<br/>

[refactor] 환경변수 설정

---

src/main/resources/application.yml

- profiles 수정
<br/>
<br/>
-
<br/>
- 
<br/>

[refactor] profiles 추가

---

src/main/java/org/example/products/service/S3Uploader.java

- 제곧내
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #100

[refactor] 퍼블릭 읽기 권한 설정

---

src/main/java/org/example/products/service/S3Uploader.java

- 
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #100

[refactor] 이미지 공개여부 재수정

---

src/main/java/org/example/common/ResponseEnum/ErrorResponseEnum.java
src/main/java/org/example/email/service/EmailServiceImpl.java

- hufs.ac.kr 외의 주소로 이메일 인증 시 에러 처리 
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #107

[refactor] 이메일 전송

---

src/main/java/org/example/common/ResponseEnum/SuccessResponseEnum.java
src/main/java/org/example/redis/RedisService.java
src/main/java/org/example/security/JwtTokenProvider.java
src/main/java/org/example/security/config/SecurityConfig.java
src/main/java/org/example/security/filter/JwtAuthenticationFilter.java
src/main/java/org/example/users/controller/UserController.java
src/main/java/org/example/users/service/UserService.java
src/main/java/org/example/users/service/UserServiceImpl.java

- 로그아웃 기능 구현
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #109

[feat]로그아웃

---

src/main/java/org/example/products/repository/ProductRepository.java
src/main/java/org/example/products/service/ProductService.java

- 제곧내
<br/>
<br/>
-
<br/>
- 서버 재부팅 후 확인 필요
<br/>
cammoa_backend #131

[refactor] 카테고리만 선택 시 마감된 게시글 안보이도록 변경

---

src/main/java/org/example/chat/controller/ChatController.java

- test api 추가해 초기 메시지 추가
<br/>
-
<br/>
- 
<br/>
cammoa_backend #134

[feat] 초기 메시지 추가

---

src/main/java/org/example/chat/dto/response/GetChatRoomsResponse.java
src/main/java/org/example/chat/dto/response/JoinChatRoomResponse.java
src/main/java/org/example/products/service/ProductService.java
src/main/java/org/example/users/service/UserServiceImpl.java

- 채팅방 목록 조회 시 product 정보 출력 
- 채팅방 참여 시 product  정보 출력
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #144

[refactor] 채팅 기능

---

src/main/java/org/example/users/controller/UserController.java
src/main/java/org/example/users/dto/response/LoginResponse.java
src/main/java/org/example/users/service/UserService.java
src/main/java/org/example/users/service/UserServiceImpl.java

- 로그인 response에 userId와 email 포함
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #148

[refactor] 로그인 responce 추가

---

src/main/java/org/example/products/dto/request/ProductUpdateRequest.java
src/main/java/org/example/products/service/ProductService.java

- 게시글 수정 리퀘스트에 인원 수 추가하여 인원 수정 가능하도록 변경
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #150

[refactor] 게시글 수정 인원 수 리퀘스트 추가

---

src/main/java/org/example/products/repository/ProductRepository.java
src/main/java/org/example/products/service/ProductService.java

- 게시글 목록 재재수정...돌겠어요
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #150

[refactor] 게시글 목록 수정

---

src/main/java/org/example/users/dto/response/LoginResponse.java
src/main/java/org/example/users/service/UserServiceImpl.java

- 로그인 완료 시 nickname 출력하도록 수정 
<br/>
<br/>
-
<br/>
- 
<br/>
cammoa_backend #169

[refactor] 로그인 기능

---

src/main/resources/application.yml

- redis port 변경
<br/>
-
<br/>
- 
<br/>

[refactor] 초기 설정 변경
